
# Gem::Specification for Ruby-do-notation-0.1
# Originally generated by Echoe

Gem::Specification.new do |s|
  s.name = %q{ruby-do-notation}
  s.version = "0.1"

  s.specification_version = 2 if s.respond_to? :specification_version=

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aanand Prasad"]
  s.date = %q{2008-06-20}
  s.description = %q{Haskell-style monad do-notation for Ruby}
  s.email = %q{aanand.prasad@gmail.com}
  s.extra_rdoc_files = ["lib/do_notation/monad.rb", "lib/do_notation/monad_plus.rb", "lib/do_notation/monads/array.rb", "lib/do_notation/monads/maybe.rb", "lib/do_notation/monads/simulations.rb", "lib/do_notation/rewriter.rb", "lib/do_notation.rb", "README.markdown"]
  s.files = ["lib/do_notation/monad.rb", "lib/do_notation/monad_plus.rb", "lib/do_notation/monads/array.rb", "lib/do_notation/monads/maybe.rb", "lib/do_notation/monads/simulations.rb", "lib/do_notation/rewriter.rb", "lib/do_notation.rb", "README.markdown", "test/array.rb", "test/maybe.rb", "test/monad_plus.rb", "test/simulations.rb", "test/spec_helper.rb", "test/specs.rb", "Manifest", "ruby-do-notation.gemspec"]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/aanand/ruby-do-notation/tree/master}
  s.rdoc_options = ["--line-numbers", "--inline-source", "--title", "Ruby-do-notation", "--main", "README.markdown"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{ruby-do-notation}
  s.rubygems_version = %q{1.1.0}
  s.summary = %q{Haskell-style monad do-notation for Ruby}

  s.add_dependency(%q<ParseTree>, [">= 0"])
  s.add_dependency(%q<ruby2ruby>, [">= 0"])
end


# # Original Rakefile source (requires the Echoe gem):
# 
# require 'spec/rake/spectask'
# 
# spec_list = FileList['test/*.rb']
# 
# task :default => :test
# 
# desc "Run all specs"
# Spec::Rake::SpecTask.new('spec') do |t|
#   t.spec_files = spec_list
# end
# 
# desc "Run all specs with RCov"
# Spec::Rake::SpecTask.new('rcov') do |t|
#   t.spec_files = spec_list
#   t.rcov = true
# end
# 
# require 'echoe'
# 
# Echoe.new('ruby-do-notation') do |p|
#   p.author = 'Aanand Prasad'
#   p.summary = 'Haskell-style monad do-notation for Ruby'
#   p.email = 'aanand.prasad@gmail.com'
#   p.url = 'http://github.com/aanand/ruby-do-notation/tree/master'
#   p.version = '0.1'
#   p.dependencies = ['ParseTree', 'ruby2ruby']
# end